version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.10"

sphinx:
  configuration: docs/conf.py  # ou conf.py si à la racine

python:
  install:
    - requirements: docs/requirements.txt  # ou requirements.txt si à la racine
